CREATE TABLE `api_league_fellow_players` (
  `id` bigint(20) NOT NULL auto_increment,
  `fellow1` varchar(45) default NULL,
  `fellow2` varchar(45) default NULL,
  `fellow3` varchar(45) default NULL,
  `fellow4` varchar(45) default NULL,
  `fellow5` varchar(45) default NULL,
  `fellow6` varchar(45) default NULL,
  `fellow7` varchar(45) default NULL,
  `fellow8` varchar(45) default NULL,
  `fellow9` varchar(45) default NULL,
  `fellow10` varchar(45) default NULL,
  `fellow11` varchar(45) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=17523 DEFAULT CHARSET=utf8;
CREATE TABLE `api_league_games` (
  `id` bigint(20) NOT NULL auto_increment,
  `gameId` bigint(20) NOT NULL,
  `championId` int(11) default NULL,
  `createDate` bigint(20) default NULL,
  `gameMode` varchar(45) default NULL,
  `gameType` varchar(45) default NULL,
  `invalid` tinyint(4) default NULL,
  `level` int(11) default NULL,
  `mapId` int(11) default NULL,
  `spell1` int(11) default NULL,
  `spell2` int(11) default NULL,
  `statRef` bigint(20) default NULL,
  `subType` varchar(45) default NULL,
  `teamId` int(11) default NULL,
  `fellowPlayerRef` bigint(20) default NULL,
  `summonerId` bigint(20) NOT NULL,
  `ipEarned` int(11) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `statRef_UNIQUE` (`statRef`),
  UNIQUE KEY `fellowPlayerRef_UNIQUE` (`fellowPlayerRef`)
) ENGINE=MyISAM AUTO_INCREMENT=15181 DEFAULT CHARSET=utf8;
CREATE TABLE `api_league_item_stats` (
  `id` bigint(20) NOT NULL,
  `FlatArmorMod` decimal(10,2) default '-1.00',
  `FlatArmorPenetrationMod` decimal(10,2) default '-1.00',
  `FlatArmorPenetrationModPerLevel` decimal(10,2) default '-1.00',
  `FlatCritChanceMod` decimal(10,2) default '-1.00',
  `FlatCritDamageMod` decimal(10,2) default '-1.00',
  `FlatDodgeMod` decimal(10,2) default '-1.00',
  `FlatDodgeModPerLevel` decimal(10,2) default '-1.00',
  `FlatGoldPer10Mod` decimal(10,2) default '-1.00',
  `FlatHPPoolMod` decimal(10,2) default '-1.00',
  `FlatHPRegenMod` decimal(10,2) default '-1.00',
  `FlatMPRegenMod` decimal(10,2) default '-1.00',
  `FlatMagicDamageMod` decimal(10,2) default '-1.00',
  `FlatMagicPenetrationMod` decimal(10,2) default '-1.00',
  `FlatMagicPenetrationModPerLevel` decimal(10,2) default '-1.00',
  `FlatMPPoolMod` decimal(10,2) default '-1.00',
  `FlatMovementSpeedMod` decimal(10,2) default '-1.00',
  `FlatPhysicalDamageMod` decimal(10,2) default '-1.00',
  `FlatSpellBlockMod` decimal(10,2) default '-1.00',
  `FlatTimeDeadMod` decimal(10,2) default '-1.00',
  `FlatTimeDeadModPerLevel` decimal(10,2) default '-1.00',
  `PercentArmorPenetrationMod` decimal(10,2) default '-1.00',
  `PercentArmorPenetrationModPerLevel` decimal(10,2) default '-1.00',
  `PercentAttackSpeedMod` decimal(10,2) default '-1.00',
  `PercentCooldownMod` decimal(10,2) default '-1.00',
  `PercentCooldownModPerLevel` decimal(10,2) default '-1.00',
  `PercentLifeStealMod` decimal(10,2) default '-1.00',
  `PercentMagicPenetrationModPerLevel` decimal(10,2) default '-1.00',
  `PercentMovementSpeedMod` decimal(10,2) default '-1.00',
  `PercentTimeDeadMod` decimal(10,2) default '-1.00',
  `PercentTimeDeadModPerLevel` decimal(10,2) default '-1.00',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `api_league_items` (
  `id` bigint(20) NOT NULL,
  `name` varchar(45) NOT NULL,
  `cost_base` int(11) NOT NULL,
  `cost_sell` int(11) NOT NULL,
  `cost_total` int(11) NOT NULL,
  `description` varchar(1000) NOT NULL,
  `img_full` varchar(45) NOT NULL,
  `img_group` varchar(45) NOT NULL,
  `img_h` int(11) NOT NULL,
  `img_w` int(11) NOT NULL,
  `img_x` int(11) NOT NULL,
  `img_y` int(11) NOT NULL,
  `img_sprite` varchar(45) NOT NULL,
  `plaintext` varchar(100) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `api_league_stats` (
  `id` bigint(20) NOT NULL auto_increment,
  `assists` int(11) default '-1',
  `barracksKilled` int(11) default '-1',
  `championsKilled` int(11) default '-1',
  `combatPlayerScore` int(11) default '-1',
  `consumablesPurchased` int(11) default '-1',
  `damageDealtPlayer` int(11) default '-1',
  `doubleKills` int(11) default '-1',
  `firstBlood` int(11) default '-1',
  `gold` int(11) default '-1',
  `goldEarned` int(11) default '-1',
  `goldSpent` int(11) default '-1',
  `item0` int(11) default '-1',
  `item1` int(11) default '-1',
  `item2` int(11) default '-1',
  `item3` int(11) default '-1',
  `item4` int(11) default '-1',
  `item5` int(11) default '-1',
  `item6` int(11) default '-1',
  `itemsPurchased` int(11) default '-1',
  `killingSprees` int(11) default '-1',
  `largestCriticalStrike` int(11) default '-1',
  `largestKillingSpree` int(11) default '-1',
  `largestMultiKill` int(11) default '-1',
  `legendaryItemsCreated` int(11) default '-1',
  `level` int(11) default '-1',
  `magicDamageDealtPlayer` int(11) default '-1',
  `magicDamageDealtToChampions` int(11) default '-1',
  `magicDamageTaken` int(11) default '-1',
  `minionsDenied` int(11) default '-1',
  `minionsKilled` int(11) default '-1',
  `neutralMinionsKilled` int(11) default '-1',
  `neutralMinionsKilledEnemyJungle` int(11) default '-1',
  `neutralMinionsKilledYourJungle` int(11) default '-1',
  `nexusKilled` tinyint(4) default '0',
  `nodeCapture` int(11) default '-1',
  `nodeCaptureAssist` int(11) default '-1',
  `nodeNeutralize` int(11) default '-1',
  `nodeNeutralizeAssist` int(11) default '-1',
  `numDeaths` int(11) default '-1',
  `numItemsBought` int(11) default '-1',
  `objectivePlayerScore` int(11) default '-1',
  `pentaKills` int(11) default '-1',
  `physicalDamageDealtPlayer` int(11) default '-1',
  `physicalDamageDealtToChampions` int(11) default '-1',
  `physicalDamageTaken` int(11) default '-1',
  `quadraKills` int(11) default '-1',
  `sightWardsBought` int(11) default '-1',
  `spell1Cast` int(11) default '-1',
  `spell2Cast` int(11) default '-1',
  `spell3Cast` int(11) default '-1',
  `spell4Cast` int(11) default '-1',
  `summonSpell1Cast` int(11) default '-1',
  `summonSpell2Cast` int(11) default '-1',
  `superMonsterKilled` int(11) default '-1',
  `team` int(11) default '-1',
  `teamObjective` int(11) default '-1',
  `timePlayed` int(11) default '-1',
  `totalDamageDealt` int(11) default '-1',
  `totalDamageDealtToChampions` int(11) default '-1',
  `totalDamageTaken` int(11) default '-1',
  `totalHeal` int(11) default '-1',
  `totalPlayerScore` int(11) default '-1',
  `totalScoreRank` int(11) default '-1',
  `totalTimeCrowdControlDealt` int(11) default '-1',
  `totalUnitsHealed` int(11) default '-1',
  `tripleKills` int(11) default '-1',
  `trueDamageDealtPlayer` int(11) default '-1',
  `trueDamageDealtToChampions` int(11) default '-1',
  `trueDamageTaken` int(11) default '-1',
  `turretsKilled` int(11) default '-1',
  `unrealKills` int(11) default '-1',
  `victoryPointTotal` int(11) default '-1',
  `visionWardsBought` int(11) default '-1',
  `wardKilled` int(11) default '-1',
  `wardPlaced` int(11) default '-1',
  `win` tinyint(4) default '0',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=44340 DEFAULT CHARSET=utf8;
CREATE TABLE `league_champs` (
  `id` int(11) NOT NULL,
  `name` varchar(45) NOT NULL,
  `default_role` int(11) NOT NULL default '-1',
  `secret_name` varchar(45) default NULL,
  `active` tinyint(4) default '1',
  `attackRank` int(11) default '0',
  `botEnabled` tinyint(4) default '0',
  `botMmEnabled` tinyint(4) default '0',
  `defenseRank` int(11) default '0',
  `difficultyRank` int(11) default '0',
  `freeToPlay` tinyint(4) default '0',
  `magicRank` int(11) default '0',
  `rankedPlayEnabled` tinyint(4) default '1',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=162 DEFAULT CHARSET=utf8;
CREATE TABLE `league_games` (
  `id` bigint(20) NOT NULL auto_increment,
  `userid` int(11) NOT NULL,
  `kills` float NOT NULL,
  `deaths` float NOT NULL,
  `assists` float NOT NULL,
  `gold` float NOT NULL,
  `minions` float NOT NULL,
  `game_type` int(11) NOT NULL default '3',
  `game_level` int(11) NOT NULL default '1',
  `date` date NOT NULL default '2013-12-17',
  `champ` int(11) NOT NULL default '-1',
  `victory` int(11) NOT NULL default '-1',
  `summoner_role` int(11) NOT NULL default '-1',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `userFK_idx` (`userid`)
) ENGINE=MyISAM AUTO_INCREMENT=813 DEFAULT CHARSET=utf8;
CREATE TABLE `league_users` (
  `id` int(11) NOT NULL auto_increment,
  `username` varchar(45) NOT NULL,
  `password` varchar(45) NOT NULL,
  `league_id` bigint(20) default NULL,
  `theme` varchar(45) default 'darkTeal',
  `display_name` varchar(45) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `username_UNIQUE` (`username`),
  UNIQUE KEY `league_id_UNIQUE` (`league_id`)
) ENGINE=MyISAM AUTO_INCREMENT=77 DEFAULT CHARSET=utf8;
